export const REQUEST_TOP_RATED = 'REQUEST_TOP_RATED'
export const RECEIVE_TOP_RATED = 'RECEIVE_TOP_RATED'
export const TOGGLE_MEUN = 'TOGGLE_MEUN'
export const CACHE_MOVIE_RESULTS = 'CACHE_MOVIE_RESULTS'

// sortMoviesArray
export const SORT_MOVIES_ARRAY = 'SORT_MOVIES_ARRAY'

// selectSingleMovie
export const ADD_LIKED_MOVIE = 'ADD_LIKED_MOVIE'
export const ADD_DISLIKED_MOVIE = 'ADD_DISLIKED_MOVIE'

export const ADD_DISLIKED_MOVIE_FROM_LIKED = 'ADD_DISLIKED_MOVIE_FROM_LIKED'
export const ADD_LIKED_MOVIE_FROM_BLOCKED = 'ADD_LIKED_MOVIE_FROM_BLOCKED'
export const REMOVE_MOVIE_FROM_LIST = 'REMOVE_MOVIE_FROM_LIST'

// ajax fail constants
export const REQUEST_FAILED = 'REQUEST_FAILED'
